In [1]:
a = 2 + 2
b = 2.0 + 2.0
c = a + b

print(f'a is an {type(a)}')
print(f'b is a {type(b)}')
print(f'c is a {type(c)}')
print(f'a / b is {a / b}')
print(f'5 / 4 is {5 / 4}')
print(f'but 5 // 4 is {5 // 4}')
print(f'and 5 % 4 is {5 % 4}')

a is an <class 'int'>
b is a <class 'float'>
c is a <class 'float'>
a / b is 1.0
5 / 4 is 1.25
but 5 // 4 is 1
and 5 % 4 is 1


In [2]:
# a list
a_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# a tuple
a_tup = (1, 2, 3, 4, 5, 6, 7, 8, 9)

# a string
a_str = 'Wil je graag een neushorn?'

# access by index
a = a_list[0]
b = a_list[-1]
c = a_list[4]
print(f'by index:\n 0 --> {a},\n-1 --> {b},\n 4 --> {c}')

# works fro strings to
print('string item at 4 --> ', a_str[4])

# you can slice a list or tuple(remember 0 indexed)
print('\nslices:')
print(a_list[2:5])
print(a_list[8:])
print(a_tup[2:5])
print(a_str[-9:])



by index:
 0 --> 1,
-1 --> 9,
 4 --> 5
string item at 4 -->  j

slices:
[3, 4, 5]
[9]
(3, 4, 5)
neushorn?


In [ ]:
# a list
a_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# a tuple
a_tup = (1, 2, 3, 4, 5, 6, 7, 8, 9)

In [ ]:
a_list[3] = 99

In [3]:
numbers = []
for i in range(3):
  for j in range(3):
    numbers.append((i, j))

numbers

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [4]:
numbers = (i, j) for i in range (3) for j in range (3)
numbers

SyntaxError: invalid syntax (1366129724.py, line 1)

In [6]:
numbers = [(i, j) for i in range (3) for j in range (3)]
numbers

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [7]:
= [n**2 for n in a]

SyntaxError: invalid syntax (1609185639.py, line 1)

In [8]:
= (n**2 for n in a)

SyntaxError: invalid syntax (536785429.py, line 1)

In [9]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# use a loop to append squared values to new lists
b = []
for n in a:
  b.append(n**2)

# or, better, use a comprehension
c = [n**2 for n in a]

print(b)
print('is the same as')
print(c)

[1, 4, 9, 16, 25, 36, 49, 64, 81]
is the same as
[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [10]:
import numpy as np

def root_mean_square(list_of_numbers):
  rms = np.sqrt(
    np.array([n**2 for n in list_of_numbers]).sum() /
    len(list_of_numbers)
    )

  return rms

l = [1.2, 3.3, 1.4, 1.4, 4.2]
rms = root_mean_square(l)

print(rms)

2.6034592372457075


In [11]:
def complain():
  print('This is boring!\nwhen will we get to the GIS stuff.\n\U0001F620\U0001F620\U0001F620\n\nSoon! Bear with me.')

complain()

This is boring!
when will we get to the GIS stuff.
😠😠😠

Soon! Bear with me.


In [12]:
zzz = print
zzz('toenails')

toenails


In [13]:
s = 'hyphens-are-everywhere-they-haunt-me-in-my-dreams'
s.split('-')

['hyphens', 'are', 'everywhere', 'they', 'haunt', 'me', 'in', 'my', 'dreams']

In [14]:
l = [(4, 3, 2), (2, 2, 2), (1, 2, 3)]

results = []

for t in l:
  results.append(
    t[0] + t[1] - t[2] +
    (t[0] * t[1] + t[2])**t[1] /
    (t[1]**2 * 5**t[0])
  )

results

[5.487822222222222, 2.36, 1.25]

In [16]:
l = [(4, 3, 2), (2, 2, 2), (1, 2, 3)]
results = [(t[0] + t[1] - t[2] +
    (t[0] * t[1] + t[2])**t[1] /
    (t[1]**2 * 5**t[0])) for t in l]

results

[5.487822222222222, 2.36, 1.25]

In [17]:
import numpy as np

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

np.array(nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

np.array(nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
def root_mean_square(list_of_numbers):
  rms = np.sqrt(
    np.array([n**2 for n in list_of_numbers]).sum() /
    len(list_of_numbers)
    )

  return rms

l = [1.2, 3.3, 1.4, 1.4, 4.2]
rms = root_mean_square(l)

print(rms)

2.6034592372457075


In [20]:
import numpy as frogz_on_crack

frogz_on_crack.array([1, 2, 3]) 

array([1, 2, 3])